name: ROS2 CI Pipeline

on:
  push:
    branches:
      - main
      # - develop
  pull_request:
    branches:
      - main
      # - develop

jobs:
  build:
    runs-on: ubuntu-22.04  # Ensure correct OS version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ROS2 Humble
        run: |
          # Ensure system is up-to-date
          sudo apt update && sudo apt upgrade -y
          
          # Install required tools
          sudo apt install -y curl gnupg lsb-release

          # Add ROS2 repository key and source list
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
          echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list
          
          # Update package list again
          sudo apt update

          # Install ROS2 Humble
          sudo apt install -y ros-humble-desktop python3-colcon-common-extensions python3-rosdep python3-vcstool build-essential

          # Initialize rosdep
          sudo rosdep init
          rosdep update

      - name: Build ROS2 Package
        run: |
          source /opt/ros/humble/setup.bash  
          colcon build --symlink-install
          
      - name: Run Tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --event-handlers console_cohesion+

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/**/test_results/**/*.xml