name: ROS2 CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Create workspace layout
      - name: Prepare workspace
        run: mkdir -p ros2_ws/src

      # Checkout your main repository into ros2_ws/src
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          path: ros2_ws/src/hcoil_pkg

      # Checkout magnetic_tentacle_interfaces into ros2_ws/src
      - name: Checkout hcoil_interfaces
        uses: actions/checkout@v4
        with:
          repository: VFrancescon/hcoil_interfaces
          path: ros2_ws/src/hcoil_interfaces

      # Install ROS2 Humble
      - name: Setup ROS2
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
          echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list
          sudo apt update
          sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions python3-rosdep python3-vcstool build-essential
          sudo rosdep init || true
          rosdep update

      # Build both packages and run tests
      - name: Build and Test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros2_ws
          rosdep install --from-paths src --ignore-src -r -y
          colcon build --symlink-install
          colcon test --return-code-on-test-failure --event-handlers console_cohesion+

      # Upload test results as artifacts
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ros2_ws/build/**/test_results/**/*.xml